### ISSUE TITLE
FontIcon: NPE if ikon property not set

### ISSUE THREAD

**Issue by AlexFalappa** [aalmiray/ikonli#16]
Forgetting to set the ikon property but setting the size as in:
``` java
FontIcon fi = new FontIcon();
fi.setIconSize(32);
jLabel.setIcon(fi);
```
leads to:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.kordamp.ikonli.swing.FontIcon.setIconSize(FontIcon.java:92)
	at af.AppFrame.<init>(AppFrame.java:15)
...
```
This is because the `font` variable in `FontIcon` is left uninitialized but used in the `setIconSize` method.

Perhaps the `ikon` property should be required as a constructor argument?

**Comment by AlexFalappa** [comment]
Are you going to release another version with the recent fixes/enhancements?

**Comment by aalmiray** [comment]
Yes, soon. I'm still collecting issues and features before publishing the next release. There were 3 issues fixed yesterday plus 4 new icon packs.
