### ISSUE TITLE
OSX Not showing properly

### ISSUE THREAD

**Issue by mataide** [aalmiray/ikonli#25]
Hello, 

I am using: `ikonli-fontawesome-pack` and `ikonli-javafx` (v2.2.0), the icons in Windows works good.
But in macOS High Sierra, all the icons shows something totally different from what it should be.

It should works in macOS as well?

**Comment by aalmiray** [comment]
@mataide: Yes, icons should work regardless of the platform. Could you post screenshots of what you're seeing? Also, it would be great if you could share more information about the environment (os version, Java version) 😄

**Comment by aalmiray** [comment]
Have you tried running the `sampler-javafx8` app? Please follow these instructions:

 1. git clone https://github.com/aalmiray/ikonli.git
 2. cd ikonli
 3. ./gradlew :sampler-javafx8:run

This app shows all icon packs in a tab per pack. If there are any conflicts between icon packs then this app will be able to show that. I just ran the app on my Mac (Sierra 10.12.15) and Java 1.8.0_162 and the icons show as expected.

**Comment by mataide** [comment]
I just found that the problem was a conflict with Controlfx: `org.controlsfx.glyphfont.FontAwesome`
You cant use both classes in the same project.

Maybe you can put a note in Readme about this.
Thanks!
