### ISSUE TITLE
OutOfMemoryException - JavaFX

### ISSUE THREAD

**Issue by andlinger** [aalmiray/ikonli#3]
Calling FontIcon#setIconLiteral many times, produces an OutOfMemoryException. 

This line is likely to be the problem:  `setStyle(getStyle() + "-fx-font-family: '" + ikonHandler.getFontFamily() + "';");`

https://github.com/aalmiray/ikonli/blob/master/subprojects/ikonli-javafx/src/main/java/org/kordamp/ikonli/javafx/FontIcon.java#L196

**Comment by aalmiray** [comment]
Hmm looks like we have to clear the previous value of `-fx-font-family` if it exists, then set the new value
