### ISSUE TITLE
Reason for executable Jars not resolving icons packs

### ISSUE THREAD

**Issue by arslancharyev31** [aalmiray/ikonli#34]
Good day.
There are several open issues (#11, #24) that have a problem of executable `jar` (with dependencies being extracted to this executable `jar`, instead of linked by manifest to their respective jars) not being able to to resolve icon packs. A workaround was proposed in [this post](https://github.com/aalmiray/ikonli/issues/11#issuecomment-367371076), that suggests to move the icon dependency up the hierarchy. I've figured out the reason why it matters: both `ikonli.core` and `ikonli.<icon pack>` have a `org.kordamp.ikonli.IkonHandler` file in `META-INF/services` directory. For the application to successfully resolve icons, the `ikonli.<icon pack>`'s version of the file has to be included in the executable `jar`.  In certain cases this can be alleviated by altering dependency order (like in IntelliJ). But in other cases (like Gradle's `jar` task) there's no way of specifying the order in which dependendencies should be extracted (or is there?). Nevertheless, the main point is that this is an issue that has to be handled by library itself, rather than leaving users of this library scratching their heads.
Your response is very much appreciated.

**Comment by aalmiray** [comment]
AFAIK multiple instances of a service file (such as `META-INF/services/org.kordamp.ikonli.IkonHandler`) are supported by the `ServiceLoader` facility added since JDK6. All matching implementations of a particular service should be loaded, regardless of the order they may appear in the classpath.

Creating a fat JAR with just the regular Gradle Jar task is *not* the way to go, as service files must be merged. This merging behavior is provided by the Gradle Shadow plugin whose setup is separate from this library.

**Comment by arslancharyev31** [comment]
Are there any specific Shadow config options that are relevant to solving the above mentioned values? Because with default shadow config I did not have much luck. To which options should one pay attention?

**Comment by aalmiray** [comment]
According to the documentation, this should be enough

    shadowJar {
        transform(ServiceFileTransformer)
    }

Or even this

    shadowJar {
        mergeServiceFiles()
    }

**Comment by leonlogli** [comment]
What about maven-shade-plugin users ?

**Comment by leonlogli** [comment]
### Problem solved
For **maven-shade-plugin** users, add this to your transformers

`<transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>`

For more information about **Resource Transformers**, [refer to this page](http://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#ServicesResourceTransformer)
