### ISSUE TITLE
Unable to build under linux: wrong Java 8 home resolution

### ISSUE THREAD

**Issue by MarceloRuiz** [aalmiray/ikonli#36]
I am having trouble building the project under Linux. I follow all the steps and set the variables correctly (actually tried both setting them to the java parent folder and to the bin folder of each version of java: /usr/lib/jvm/java-X-oracle/ and /usr/lib/jvm/java-X-oracle/bin/) but the resolution of java8 home fails in both cases (it adds the bin folder twice:

`
marcelo@marcelo-desktop:/tmp/ikonli$ **export JAVA_8=/usr/lib/jvm/java-8-oracle/**

marcelo@marcelo-desktop:/tmp/ikonli$ **export JAVA_9=/usr/lib/jvm/java-9-oracle/**

marcelo@marcelo-desktop:/tmp/ikonli$ **echo $JAVA_8**
/usr/lib/jvm/java-8-oracle/

marcelo@marcelo-desktop:/tmp/ikonli$ **ls $JAVA_8**
bin  COPYRIGHT  include  javafx-src.zip  jre  lib  LICENSE  man  README.html  release  src.zip  THIRDPARTYLICENSEREADME-JAVAFX.txt  THIRDPARTYLICENSEREADME.txt

marcelo@marcelo-desktop:/tmp/ikonli$ **echo $JAVA_9**
/usr/lib/jvm/java-9-oracle/

marcelo@marcelo-desktop:/tmp/ikonli$ **ls $JAVA_9**
appletviewer  jar  javac  javap  javaws.real  jcontrol  jdeps  jinfo  jmap  jps  jstack  jweblauncher  pack200  rmid  serialver  unpack200  xjc  idlj  jarsigner  javadoc  javapackager  jcmd  jdb  jhsdb jjs jmc  jrunscript  stat  keytool  policytool  rmiregistry  servertool  wsgen  jaotc  java  javah  javaws  jconsole  jdeprscan  jimage  link  jmod  jshell  jstatd  orbd  rmic  schemagen  tnameserv  wsimport

marcelo@marcelo-desktop:/tmp/ikonli$ **./gradlew build**
> Task :ikonli-javafx:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ikonli-javafx:compileJava'.
> The supplied javaHome seems to be invalid. I cannot find the java executable. **Tried location: /usr/lib/jvm/java-8-oracle/bin/bin/java**

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 10s
123 actionable tasks: 58 executed, 65 up-to-date

marcelo@marcelo-desktop:/tmp/ikonli$
`

**Comment by aalmiray** [comment]
This should no longer be a problem since version `11.0.0` moved to Java/JavaFX 11.
