### ISSUE TITLE
Provide artifacts on Maven central

### ISSUE THREAD

**Issue by hendrikebbers** [aalmiray/ikonli#4]
Some people still use Maven ;)

**Comment by aalmiray** [comment]
No need to push to Maven Central. Simply configure a `repositories` block in the POM file

    <repositories>
        <repository>
            <id>jcenter</id>
            <url>http://jcenter.bintray.com/</url>
        </repository>
    </repositories>

**Comment by aalmiray** [comment]
Version `1.9.0` can now be found in Maven central
