### ISSUE TITLE
Can't import font icons in Scene Builder 11

### ISSUE THREAD

**Issue by drjosephliu** [aalmiray/ikonli#41]
I'm using JavaFX 11, JRE 11 and Scene Builder 11. 

When I try to import ikonli-javafx-11.0.2.jar into Scene Builder the only components I get are FontIconTableCell and StackedFontIcon.

How can I get font icons?

**Comment by aalmiray** [comment]
You must configure `ikonli-core` and `ikonli-javafx`. This gives you access to the `FontIcon` class. You should also include at least 1 icon pack (such as  `ikonli-fontawesome-pack`) like it's shown in the following picture

<img width="1258" alt="ikonli-scenebuilder" src="https://user-images.githubusercontent.com/13969/50362513-9ef47980-052d-11e9-837f-60fced61e9c1.png">
