### ISSUE TITLE
SceneBuilder 11 false display after import ikonli 11

### ISSUE THREAD

**Issue by phamvanthanh** [aalmiray/ikonli#47]

**Comment by phamvanthanh** [comment]
Hi,
This is quite strange 
![image](https://user-images.githubusercontent.com/24784468/55735825-4d281e80-5a4c-11e9-8d23-7c1db863344d.png)

**Comment by phamvanthanh** [comment]
Cannot import items too. (javafx, core are imported)
![image](https://user-images.githubusercontent.com/24784468/55737480-739b8900-5a4f-11e9-882b-bd2ba34b6de1.png)

**Comment by aalmiray** [comment]
Have you looked at https://github.com/aalmiray/ikonli/issues/41? What does the "About" menu say on SceneBuilder?

**Comment by phamvanthanh** [comment]
![image](https://user-images.githubusercontent.com/24784468/55740513-70a39700-5a55-11e9-92ea-22259bf455c5.png)

I reported to Gluon.

Got the icons. Awesome!
Thank you
