### ISSUE TITLE
FontAwesome5 pack not rendering icons in version 11.3.0

### ISSUE THREAD

**Issue by byron-dm** [aalmiray/ikonli#49]
I'm currently working on Windows 10 Pro with Gradle. I updated from v11.1.0 which was working perfectly with JDK and JavaFX 11/12 to v11.3.0 and now all I get is an empty rectangle instead of icons.

According to https://github.com/aalmiray/ikonli/issues/48, it was already fixed, but I'm unable to make it work.

**Comment by aalmiray** [comment]
Which icon pack are you using? Do you have both `ikonli-core` and `ikonli-javafx` dependencies set in your project?

**Comment by byron-dm** [comment]
Version 11.3.1 fixed this; didn't have to include ikonli-core, only ikonli-javafx and fontawesome5-pack.

**Comment by chrismaster** [comment]
With 11.3.0 and 11.3.1 I have to add explicit ikonli-core or i get
    error: cannot access Ikon  new FontIcon("fa-question"));
With 11.2.0 I didn't have to add ikonli-core

**Comment by aalmiray** [comment]
A side effect of using the `implementation` configuration instead of `api`. This sets in the pom.xml the `ikonli-core` dependency in `runtime` scope instead of `compile`. Will fix soon.
