### ISSUE TITLE
i"k"onli or i"c"onli

### ISSUE THREAD

**Issue by sormuras** [aalmiray/ikonli#56]
Here's a `c`:

https://github.com/aalmiray/ikonli/blob/8f497371aafd93667fa8e7f1b8e7225981e03e97/core/ikonli-core/src/main/java/module-info.java#L18

Here are `k`s:
- `core/ikonli-core` directory
- `package org.kordamp.ikonli;` in "core"

**Comment by aalmiray** [comment]
Oops, it should be `ikonli`.

**Comment by sormuras** [comment]
It's referred to in all other `module-info.java` files. ;-)

**Comment by sormuras** [comment]
While you're at it -- what about making the module name match the package name?

`module org.kordamp.iconli` reads better.

**Comment by aalmiray** [comment]
Renaming modules means breaking compatibility ... oh well

**Comment by sormuras** [comment]
We're all still learning...

...and I found a bunch of bugs and missing features in Bach while building **ikonli**. 😉

**Comment by aalmiray** [comment]
Yay! (?) As long as we can improve and make things better 😄 👏

**Comment by sormuras** [comment]
> As long as we can improve and make things better

🚀
