### ISSUE TITLE
cannot access org.kordamp.ikonli.Ikon   class file for org.kordamp.ikonli.Ikon not found

### ISSUE THREAD

**Issue by rahmanusta** [aalmiray/ikonli#6]
Hey @aalmiray, What is missing here ?

![image](https://cloud.githubusercontent.com/assets/1158804/19243200/5268e460-8f1f-11e6-9cd3-649a9801e7b3.png)

**Comment by aalmiray** [comment]
Did you include the `ikonli-core` dependency?

**Comment by rahmanusta** [comment]
Ah, it was like it resolved it already but I overlooked it.

I've needed 4 dependencies;

```xml
        <dependency>
            <groupId>org.kordamp.jipsy</groupId>
            <artifactId>jipsy</artifactId>
            <version>0.4.0</version>
        </dependency>
        <dependency>
            <groupId>org.kordamp.ikonli</groupId>
            <artifactId>ikonli-core</artifactId>
            <version>1.7.0</version>
        </dependency>
        <dependency>
            <groupId>org.kordamp.ikonli</groupId>
            <artifactId>ikonli-javafx</artifactId>
            <version>1.7.0</version>
        </dependency>
        <dependency>
            <groupId>org.kordamp.ikonli</groupId>
            <artifactId>ikonli-fontawesome-pack</artifactId>
            <version>1.7.0</version>
        </dependency>
```

What do you think to resolve some of them transitively ?

Thank you!

**Comment by aalmiray** [comment]
AFAIK `ikonli-javafx` pulls in `ikonli-core` as a transitive dependency. `jipsy` is only needed if you intend to build your own icon packs. Icon packs OTOH only pull in `ikonli-core` as they do not target an specific UI toolkit such as `swing` or `javafx`.

I'm a bit surprised that the transitive dependencies did not work, I haven't encountered a problem when defining just `ikonli-javafx` and an icon pack with Gradle.

**Comment by aalmiray** [comment]
Aha! I think I see where the problem lies, `ikonli-javafx` defines the following dependency

    <dependencies>
      <dependency>
        <groupId>org.kordamp.ikonli</groupId>
        <artifactId>ikonli-core</artifactId>
        <version>1.7.0</version>
        <scope>runtime</scope>
      </dependency>
    </dependencies>

Notice the usage of `runtime` scope. This is a side effect of the default POM marshalling that the `maven-publish` Gradle plugin applies to a POM file.

**Comment by rahmanusta** [comment]
I suppose it is because ikonli-core's scope is runtime and Ikon class is needed at compile time, at least in maven.

**Comment by aalmiray** [comment]
Yup, the fix is to publish new POMs that do not have `runtime` scope.

**Comment by rahmanusta** [comment]
Thank you! In addition ikonli works without jipsy dependency, FYI.

**Comment by aalmiray** [comment]
Indeed, `jipsy` is a compile only dependency. In Maven speak it's in `provided` scope.

**Comment by rahmanusta** [comment]
:+1:
